# encoding: utf-8

require File.expand_path('lib/backup/version')

Gem::Specification.new do |gem|
  gem.name        = 'backup'
  gem.version     = Backup::VERSION
  gem.platform    = Gem::Platform::RUBY
  gem.authors     = 'Michael van Rooijen'
  gem.email       = 'meskyanichi@gmail.com'
  gem.homepage    = 'https://github.com/backup/backup'
  gem.license     = 'MIT'
  gem.summary     = 'Provides an elegant DSL in Ruby for performing backups on UNIX-like systems.'
  gem.description = <<-EOS.gsub(/\s+/, ' ').strip
    Backup is a RubyGem, written for UNIX-like operating systems, that allows you to easily perform backup operations
    on both your remote and local environments. It provides you with an elegant DSL in Ruby for modeling your backups.
    Backup has built-in support for various databases, storage protocols/services, syncers, compressors, encryptors
    and notifiers which you can mix and match. It was built with modularity, extensibility and simplicity in mind.
  EOS

  gem.files = %x[git ls-files -- lib bin templates README.md LICENSE.md].split("\n")
  gem.require_path  = 'lib'
  gem.executables   = ['backup']

  gem.required_ruby_version = '>= 2.0'

  # Gem Dependencies
  # Generated by `rake gemspec`. Do Not Edit.
  gem.add_dependency 'CFPropertyList'
  gem.add_dependency 'addressable'
  gem.add_dependency 'atomic'
  gem.add_dependency 'aws-ses'
  gem.add_dependency 'buftok'
  gem.add_dependency 'builder'
  gem.add_dependency 'descendants_tracker'
  gem.add_dependency 'dogapi'
  gem.add_dependency 'dropbox-sdk'
  gem.add_dependency 'equalizer'
  gem.add_dependency 'excon'
  gem.add_dependency 'faraday'
  gem.add_dependency 'fission'
  gem.add_dependency 'flowdock'
  gem.add_dependency 'fog'
  gem.add_dependency 'fog-atmos'
  gem.add_dependency 'fog-aws'
  gem.add_dependency 'fog-brightbox'
  gem.add_dependency 'fog-core'
  gem.add_dependency 'fog-ecloud'
  gem.add_dependency 'fog-json'
  gem.add_dependency 'fog-profitbricks'
  gem.add_dependency 'fog-radosgw'
  gem.add_dependency 'fog-riakcs'
  gem.add_dependency 'fog-sakuracloud'
  gem.add_dependency 'fog-serverlove'
  gem.add_dependency 'fog-softlayer'
  gem.add_dependency 'fog-storm_on_demand'
  gem.add_dependency 'fog-terremark'
  gem.add_dependency 'fog-vmfusion'
  gem.add_dependency 'fog-voxel'
  gem.add_dependency 'fog-xml'
  gem.add_dependency 'formatador'
  gem.add_dependency 'hipchat'
  gem.add_dependency 'http'
  gem.add_dependency 'http_parser.rb'
  gem.add_dependency 'httparty'
  gem.add_dependency 'inflecto'
  gem.add_dependency 'ipaddress'
  gem.add_dependency 'json'
  gem.add_dependency 'mail'
  gem.add_dependency 'memoizable'
  gem.add_dependency 'mime-types'
  gem.add_dependency 'mini_portile'
  gem.add_dependency 'multi_json'
  gem.add_dependency 'multi_xml'
  gem.add_dependency 'multipart-post'
  gem.add_dependency 'net-scp'
  gem.add_dependency 'net-sftp'
  gem.add_dependency 'net-ssh'
  gem.add_dependency 'nokogiri'
  gem.add_dependency 'open4'
  gem.add_dependency 'pagerduty'
  gem.add_dependency 'polyglot'
  gem.add_dependency 'simple_oauth'
  gem.add_dependency 'thor'
  gem.add_dependency 'thread_safe'
  gem.add_dependency 'treetop'
  gem.add_dependency 'twitter'
  gem.add_dependency 'unf'
  gem.add_dependency 'unf_ext'
  gem.add_dependency 'xml-simple'
end
